on: 
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')   
    runs-on: ubuntu-latest
    steps:
      # Run the example action
      - name: Fast Forward action
        id: ff-action
        uses:  endre-spotlab/fast-forward-js-action@1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed!  Cannot do a fast forward from ***target_base*** to ***source_head***! 1) Please try to ```git checkout source_head && git rebase target_base```. Then recreate the Pull Request. 2) Or merge using _Merge pull request_ button. Then delete ***source_head*** branch, and recreate from merged ***target_base*** branch.'
          close_pr: 'false'