on: 
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')   
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Run the example action
      - name: Fast Forward action
        id: ff-action
        uses:  ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Possible reasons: 1) ***ff_fail_reason*** 2) Review required, pull-request is not approved 3) Some status checks were not successful (like build check) '
          production_branch: 'master'
          staging_branch: 'stage'