on: 
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')   
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Run the example action
      - name: Fast Forward action
        id: ff-action
        uses: ./
        with:
          in-value: 'Endre Input Value'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast Forward action executed!'
          failure_message: 'Failed!  Cannot do a fast forward! 1) Please try to checkout source (head) branch, and then rebase it onto target (base) branch. Then recreate the Pull Request. 2) Or merge using _Merge pull request_ button. Then delete source (head) branch, and recreate from merged target (base) branch.'
          close_pr: 'false'

      # Use the output from the previous step
      - name: Get the output time
        run: echo "The time was ${{ steps.ff-action.outputs.out-value }}"